import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

/**
 * Database plumbing for this package's integration tier (TDS 07 §3).
 *
 * Deliberately simpler than the Backend's: that tier runs 26 files in parallel and pays for a
 * `CREATE DATABASE … TEMPLATE` machine to keep them isolated. This one has a handful of files,
 * runs them serially, and therefore needs one migrated database per run and nothing else.
 *
 * Dependency-light and side-effect-free on import — it runs inside Vitest's `globalSetup`,
 * before any application module is loaded.
 */

export const TEST_DATABASE_PREFIX = 'mc_tgw_test_';

export function repoRoot(): string {
  // .../apps/telegram-worker/test/integration/database.ts -> repo root
  return resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
}

/** Where the drizzle migration set lives (TDS 03 §8: the SQL in these files is what runs). */
export function migrationsFolder(): string {
  return join(repoRoot(), 'packages', 'shared', 'drizzle');
}

/**
 * `TEST_DATABASE_URL` — an admin connection to the local instance, the only test-specific
 * bootstrap variable (TDS 07 §3.1). Test tooling only: no application code reads it, so the
 * F8.2 variable set stays locked. Real process env wins over the root `.env`, matching the
 * loader's precedence; tests never write or modify `.env`.
 */
export function testDatabaseAdminUrl(): string {
  const fromEnv = process.env['TEST_DATABASE_URL'];
  if (typeof fromEnv === 'string' && fromEnv.length > 0) return fromEnv;

  const envFile = join(repoRoot(), '.env');
  if (existsSync(envFile)) {
    for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
      const match = /^\s*(?:export\s+)?TEST_DATABASE_URL\s*=\s*(.*?)\s*$/.exec(line);
      const value = match?.[1]?.replace(/^["']|["']$/g, '');
      if (value !== undefined && value.length > 0) return value;
    }
  }

  throw new Error(
    'TEST_DATABASE_URL is not set.\n' +
      '  The integration tier needs an admin connection to a local PostgreSQL instance\n' +
      '  (a role with CREATEDB). Add TEST_DATABASE_URL to the root .env or the environment.\n' +
      '  See docs/tds/07-test-strategy.md §3.2.',
  );
}

/** Swap the database name in a connection string, keeping every other parameter. */
export function withDatabaseName(connectionString: string, database: string): string {
  const url = new URL(connectionString);
  url.pathname = `/${database}`;
  return url.toString();
}

export async function withAdminClient<T>(
  adminUrl: string,
  run: (client: pg.Client) => Promise<T>,
): Promise<T> {
  const client = new pg.Client({ connectionString: adminUrl, connectionTimeoutMillis: 5_000 });

  try {
    await client.connect();
  } catch (error) {
    throw new Error(
      'PostgreSQL not reachable at TEST_DATABASE_URL — see docs/tds/07-test-strategy.md §3.2\n' +
        `  (${(error as Error).message})`,
    );
  }

  try {
    return await run(client);
  } finally {
    await client.end();
  }
}

/**
 * Identifier quoting for the one place this harness interpolates a name into DDL:
 * `CREATE DATABASE` and `DROP DATABASE` cannot take parameters. Every name reaching here is
 * generated by this file, and the assertion keeps it that way.
 */
export function quoteIdentifier(name: string): string {
  if (!/^[a-z0-9_]+$/.test(name)) throw new Error(`Refusing to quote identifier: ${name}`);
  return `"${name}"`;
}

/**
 * Drop a disposable database.
 *
 * `WITH (FORCE)` terminates leftover connections (PostgreSQL 13+), which is what makes a
 * crashed run self-healing. `55006` (a session is still attached) and `42501` (an autovacuum
 * worker owned by the bootstrap superuser cannot be signalled by a plain role) are races
 * against background processes, not misconfiguration, so they are retried rather than failing
 * the run over pure flake (TDS 07 §11.3).
 */
export async function dropDatabase(client: pg.Client, name: string): Promise<void> {
  const statement = `DROP DATABASE IF EXISTS ${quoteIdentifier(name)} WITH (FORCE)`;

  for (let attempt = 0; ; attempt += 1) {
    try {
      await client.query(statement);
      return;
    } catch (error) {
      const code = (error as { code?: string }).code;
      if ((code !== '55006' && code !== '42501') || attempt >= 30) throw error;
      await new Promise((resolve) => setTimeout(resolve, 100 + attempt * 50));
    }
  }
}

/** Drop every abandoned database this package left behind; a crashed run leaves no sessions. */
export async function sweepOrphans(client: pg.Client): Promise<void> {
  const result = await client.query<{ datname: string }>(
    `SELECT d.datname FROM pg_database d
      WHERE d.datname LIKE $1
        AND NOT EXISTS (SELECT 1 FROM pg_stat_activity a WHERE a.datname = d.datname)`,
    [`${TEST_DATABASE_PREFIX}%`],
  );

  for (const row of result.rows) await dropDatabase(client, row.datname);
}
