import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

/**
 * Shared plumbing for the integration database tier (TDS 07 §3.1): one migrated **template**
 * database, and a per-worker `CREATE DATABASE … TEMPLATE` clone.
 *
 * Deliberately dependency-light and self-contained — it runs inside Vitest's `globalSetup`,
 * before any application module is loaded, and it must not create `MC_DATA_DIR` or otherwise
 * have side effects just by being imported.
 */

export const TEMPLATE_DATABASE = 'mc_test_template';
export const TEST_DATABASE_PREFIX = 'mc_test_';

/** Where the drizzle migration set lives (TDS 03 §8: the SQL in these files is what runs). */
export function migrationsFolder(): string {
  return join(repoRoot(), 'packages', 'shared', 'drizzle');
}

export function repoRoot(): string {
  // .../apps/backend/test/integration/database.ts -> repo root
  return resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
}

/**
 * `TEST_DATABASE_URL` — an admin connection to the local instance, the only test-specific
 * bootstrap variable (TDS 07 §3.1). Test tooling only: no application code reads it, so the
 * F8.2 variable set stays locked.
 *
 * Real process env wins over the root `.env`, matching the loader's precedence; tests never
 * write or modify `.env`.
 */
export function testDatabaseAdminUrl(): string {
  const fromEnv = process.env['TEST_DATABASE_URL'];
  if (typeof fromEnv === 'string' && fromEnv.length > 0) return fromEnv;

  const envFile = join(repoRoot(), '.env');
  if (existsSync(envFile)) {
    for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
      const match = /^\s*(?:export\s+)?TEST_DATABASE_URL\s*=\s*(.*?)\s*$/.exec(line);
      const value = match?.[1]?.replace(/^["']|["']$/g, '');
      if (value !== undefined && value.length > 0) return value;
    }
  }

  throw new Error(
    'TEST_DATABASE_URL is not set.\n' +
      '  The integration tier needs an admin connection to a local PostgreSQL instance\n' +
      '  (a role with CREATEDB). Add TEST_DATABASE_URL to the root .env or the environment.\n' +
      '  See docs/tds/07-test-strategy.md §3.2.',
  );
}

/** Swap the database name in a connection string, keeping every other parameter. */
export function withDatabaseName(connectionString: string, database: string): string {
  const url = new URL(connectionString);
  url.pathname = `/${database}`;
  return url.toString();
}

export async function withAdminClient<T>(
  adminUrl: string,
  run: (client: pg.Client) => Promise<T>,
): Promise<T> {
  const client = new pg.Client({ connectionString: adminUrl, connectionTimeoutMillis: 5_000 });

  try {
    await client.connect();
  } catch (error) {
    throw new Error(
      `PostgreSQL not reachable at TEST_DATABASE_URL — see docs/tds/07-test-strategy.md §3.2\n` +
        `  (${(error as Error).message})`,
    );
  }

  try {
    return await run(client);
  } finally {
    await client.end();
  }
}

/**
 * Identifier quoting for the one place this harness interpolates a name into DDL:
 * `CREATE DATABASE` and `DROP DATABASE` cannot take parameters. Every name reaching here is
 * generated by this file (`mc_test_…`), and the assertion keeps it that way.
 */
export function quoteIdentifier(name: string): string {
  if (!/^[a-z0-9_]+$/.test(name)) throw new Error(`Refusing to quote identifier: ${name}`);
  return `"${name}"`;
}

/** A content hash of the migration set — the template is rebuilt when this changes. */
export function migrationSetHash(): string {
  const folder = migrationsFolder();
  const hash = createHash('sha256');

  for (const entry of readdirSync(folder).sort()) {
    if (!entry.endsWith('.sql')) continue;
    hash.update(entry);
    hash.update(readFileSync(join(folder, entry)));
  }

  const journal = join(folder, 'meta', '_journal.json');
  if (existsSync(journal)) hash.update(readFileSync(journal));

  return hash.digest('hex');
}

export async function databaseExists(client: pg.Client, name: string): Promise<boolean> {
  const result = await client.query('SELECT 1 FROM pg_database WHERE datname = $1', [name]);
  return result.rowCount === 1;
}

export async function dropDatabase(client: pg.Client, name: string): Promise<void> {
  // WITH (FORCE) terminates leftover connections (PostgreSQL 13+), which is what makes a
  // crashed run self-healing instead of requiring a manual cleanup.
  await client.query(`DROP DATABASE IF EXISTS ${quoteIdentifier(name)} WITH (FORCE)`);
}

/**
 * `CREATE DATABASE … TEMPLATE` fails with 55006 while any session is connected to the
 * template. Parallel workers cloning at once is the normal case, so retry briefly rather
 * than making the tier serial.
 */
export async function createDatabaseFromTemplate(
  client: pg.Client,
  name: string,
  template: string,
): Promise<void> {
  const statement = `CREATE DATABASE ${quoteIdentifier(name)} TEMPLATE ${quoteIdentifier(template)}`;

  for (let attempt = 0; ; attempt += 1) {
    try {
      await client.query(statement);
      return;
    } catch (error) {
      const code = (error as { code?: string }).code;
      if (code !== '55006' || attempt >= 20) throw error;
      await new Promise((r) => setTimeout(r, 100 + attempt * 50));
    }
  }
}
