import {
  categoryWriteSchema,
  DOCUMENT_CATEGORIES,
  type DocumentCategory,
  INTEGRATION_SLUGS,
  type IntegrationSlug,
  type IntegrationsSettings,
  integrationWriteSchema,
  isDocumentCategory,
  type SettingsDocument,
  type TestConnectionResult,
} from '@mc/shared';
import type { FastifyInstance } from 'fastify';
import { requirePrincipal } from '../auth/guard.js';
import type { Principal } from '../auth/principal.js';
import { type RequestContext, requestContextOf } from '../http/context.js';
import { ApiError, dataEnvelope } from '../http/errors.js';

/**
 * `/api/v1/settings/*` — TDS 04 §7.3–§7.4, path for path.
 *
 *   GET  /api/v1/settings                                            every category, masked
 *   GET  /api/v1/settings/{category}                                 general|notifications|memory|agents|security
 *   PUT  /api/v1/settings/{category}                                 full-category replace (A14)
 *   GET  /api/v1/settings/integrations                               all six, secrets masked
 *   PUT  /api/v1/settings/integrations/{integration}                 one integration, masked answer
 *   POST /api/v1/settings/integrations/{integration}/test-connection
 *
 * **Every write path is a static route with its own schema**, generated by looping over the
 * key registry (§7.6) — eleven `PUT`s and six `POST`s, declared once in code. The alternative,
 * one parametric route validating a schema chosen inside the handler, would have put settings
 * validation on a second stack with its own error shape; this way Fastify's own Ajv rejects a
 * bad body in the F5.4 envelope, exactly as it does for every other route, and the schemas are
 * attached where OpenAPI generation (F5.1) will later find them.
 *
 * `integrations` is deliberately not reachable through `PUT /settings/{category}`: it is read
 * whole and written one integration at a time (§7.3), and a full-category replace of all six
 * would include three secrets a client is forbidden to read and therefore cannot resend.
 */

const categoryParamsSchema = {
  type: 'object',
  required: ['category'],
  additionalProperties: false,
  properties: { category: { type: 'string', maxLength: 32 } },
} as const;

/**
 * The body of the parametric `PUT` fallback is deliberately **not** inspected
 * (`http/body-strictness.ts`), and this is the one place in the product where that is right.
 *
 * That route matches only categories that have no static route, so it does exactly one thing:
 * throw `NOT_FOUND` for the category. Holding the body to an empty allowlist would answer
 * `PUT /settings/favourites { "theme": "light" }` with "unknown body field: theme" — a
 * complaint about the fields of a resource that does not exist, which names the wrong problem
 * and hides the real one.
 */
const uninspectedBodySchema = { type: 'object', additionalProperties: true } as const;

interface CategoryParams {
  category: string;
}

/**
 * What the routes need from the domain, as an interface rather than the class — so the route
 * layer is unit testable with no database (TDS 07 §1) and `http/` keeps owning no business
 * logic (TDS 02 §2).
 */
export interface SettingsPort {
  readAll(): Promise<SettingsDocument>;
  readCategory(category: DocumentCategory): Promise<Record<string, unknown>>;
  readIntegrations(): Promise<IntegrationsSettings>;
  replaceCategory(
    principal: Principal,
    category: DocumentCategory,
    body: unknown,
    ctx: RequestContext,
  ): Promise<Record<string, unknown>>;
  replaceIntegration(
    principal: Principal,
    slug: IntegrationSlug,
    body: unknown,
    ctx: RequestContext,
  ): Promise<Record<string, unknown>>;
}

export interface TestConnectionPort {
  run(slug: IntegrationSlug): Promise<TestConnectionResult>;
}

export interface SettingsRoutesOptions {
  readonly settings: SettingsPort;
  readonly testConnection: TestConnectionPort;
}

export function registerSettingsRoutes(app: FastifyInstance, options: SettingsRoutesOptions): void {
  const { settings, testConnection } = options;

  app.get('/api/v1/settings', async () => dataEnvelope(await settings.readAll()));

  // ------------------------------------------------------------------------- integrations

  app.get('/api/v1/settings/integrations', async () =>
    dataEnvelope(await settings.readIntegrations()),
  );

  for (const slug of INTEGRATION_SLUGS) {
    app.put<{ Body: unknown }>(
      `/api/v1/settings/integrations/${slug}`,
      { schema: { body: integrationWriteSchema(slug) } },
      async (request) =>
        dataEnvelope(
          await settings.replaceIntegration(
            requirePrincipal(request),
            slug,
            request.body,
            requestContextOf(request),
          ),
        ),
    );

    // §7.4: a completed check is a 200 whatever the outcome; only a *refused request*
    // (`INTEGRATION_NOT_CONFIGURED`) is an error envelope. No body — the check reads
    // persisted settings, so testing unsaved input is unrepresentable here.
    app.post(`/api/v1/settings/integrations/${slug}/test-connection`, async () =>
      dataEnvelope(await testConnection.run(slug)),
    );
  }

  // ----------------------------------------------------------------- document categories

  for (const category of DOCUMENT_CATEGORIES) {
    app.put<{ Body: unknown }>(
      `/api/v1/settings/${category}`,
      { schema: { body: categoryWriteSchema(category) } },
      async (request) =>
        dataEnvelope(
          await settings.replaceCategory(
            requirePrincipal(request),
            category,
            request.body,
            requestContextOf(request),
          ),
        ),
    );
  }

  // The parametric routes come last and match only what the static ones did not: an unknown
  // category on GET, and any category at all on PUT that has no static route above.
  app.get<{ Params: CategoryParams }>(
    '/api/v1/settings/:category',
    { schema: { params: categoryParamsSchema } },
    async (request) => dataEnvelope(await settings.readCategory(documentCategory(request.params))),
  );

  app.put<{ Params: CategoryParams }>(
    '/api/v1/settings/:category',
    { schema: { params: categoryParamsSchema, body: uninspectedBodySchema } },
    async (request) => {
      // Always throws: every writable category has its own static route above.
      documentCategory(request.params);
      throw new ApiError('NOT_FOUND', `Unknown settings category "${request.params.category}"`);
    },
  );
}

function documentCategory(params: CategoryParams): DocumentCategory {
  if (isDocumentCategory(params.category)) return params.category;

  if (params.category === 'integrations') {
    throw new ApiError(
      'VALIDATION_FAILED',
      'Integrations are read at GET /settings/integrations and written one at a time at PUT /settings/integrations/{integration} (§7.3)',
      { category: 'integrations', integrations: [...INTEGRATION_SLUGS] },
    );
  }

  // §7.3: `NOT_FOUND` for an unknown category.
  throw new ApiError('NOT_FOUND', `Unknown settings category "${params.category}"`, {
    known: [...DOCUMENT_CATEGORIES, 'integrations'],
  });
}
